### ISSUE TITLE
Custom utilities with group-hover ?

### ISSUE THREAD

**Issue by patrikengborg** [tailwindcss/discuss#102]
I have defined two classes as custom utilities (placed after @tailwind utilities)

```
.scale-0 { transform:scale(0); }
.scale-1 { transform:scale(1); }
```

How can I make them work together with group-hover? No modules are enabled to work with group-hover by default and needs to be enabled in tailwind.js, but my custom utility classes aren't even represented in the modules object. Is there a way around this?

Thanks.

**Comment by adamwathan** [comment]
Hey @patrikengborg! You can use the [`@variants` directive](https://tailwindcss.com/docs/functions-and-directives#variants) for this:

```css
@variants group-hover {
  .scale-0 { transform:scale(0); }
  .scale-1 { transform:scale(1); }
}
```
