### ISSUE TITLE
@responsive directive not working with css-loader local modules

### ISSUE THREAD

**Issue by paschaldev** [tailwindcss/discuss#105]
Trying to generate responsive classes with the `@responsive` directive is not working as expected. I'm using `webpack` and `postcss` and I'm using local module to transform class names.

### Input 

```css
@responsive{

    :local( .form__input--exposed ) {

        @apply .border-none .border-0;
    }
}
```

### Sample Output

```css
.sm_local( .form__input--exposed ) {

    border-style: none;
    border-width: 0;
}
```
