### ISSUE TITLE
Plugins: Adding responsive variants to a nested class?

### ISSUE THREAD

**Issue by bradgenereux** [tailwindcss/discuss#133]
I'm trying to create a plugin that adds "safe-area" padding utilities for the iPhone X notch. For those unfamiliar with this, there's a great article on it here. https://webkit.org/blog/7929/designing-websites-for-iphone-x/

This is what I have so far:
```js
const _ = require('lodash')

module.exports = function ({ suffix = 'safe', variants = ['responsive'] }) {
    return function ({ addUtilities, e, config }) {
        padding = config('padding', []);

        addUtilities([
            _.map(padding, (value, name) => {
                return {
                    [`.px-${e(name)}-${e(suffix)}`]: { 
                        paddingLeft: value,
                        paddingRight: value,
                    },
                    '@supports(padding: max(0px))': { 
                        [`.px-${e(name)}-${e(suffix)}`]: { 
                            paddingLeft: `max(${value}, env(safe-area-inset-left))`,
                            paddingRight: `max(${value}, env(safe-area-inset-right))`,
                        },
                    },
                }
            })
        ], variants)
    }
}
```
And here's the output:

```css
.px-4-safe {
    padding-left: 1rem;
    padding-right: 1rem;
}

@supports(padding: max(0px)) {
    .px-4-safe {
        padding-left: max(1rem, env(safe-area-inset-left));
        padding-right: max(1rem, env(safe-area-inset-right));
    }
}

@media (min-width: 576px) {
    .sm\:px-4-safe {
        padding-left: 1rem;
        padding-right: 1rem;
    }
    
    @supports(padding: max(0px)) {
        .px-4-safe {
            padding-left: max(1rem, env(safe-area-inset-left));
            padding-right: max(1rem, env(safe-area-inset-right));
        }
    }
}
```

It's close, but the ```sm\:``` prefix isn't being added to the class nested inside the ```@supports``` tag. I'm wondering if anyone knows how I might accomplish this?

**Comment by bradgenereux** [comment]
I was not able to automatically generate safe-areas for each screen size as attempted in my original post, though it's probably not even necessary. I ended up just manually creating the 2 utilities that I needed, basically ```px-4-safe``` and ```pb-6-safe```. The ```px-4-safe``` utility protects you from the notch and rounded corners while in landscape mode, and the ```pb-6-safe``` utility prevents the Home Bar from covering content.

As for the link you posted, I think safe-areas are a better solution than shrinking the screen width, simply because safe-areas are Apple's official solution to the problem.

So for the code you posted it might look something like this:
```html
<header class="fixed pin-t pin-l pin-r px-4-safe">
    Header Content
</header>
<main class="px-4-safe">
    Body Content
</main>
<footer class="px-4-safe pb-6-safe">
    Footer Content
</footer>
```

Here's what my safe-area utilities file for reference:

```css
.px-4-safe {
    padding-left: 1rem;
    padding-right: 1rem;
}

@supports(padding: max(0px)) {
    .px-4-safe {
        padding-left: ~"max(1rem, env(safe-area-inset-left))";
        padding-right: ~"max(1rem, env(safe-area-inset-right))";
    }
}

.pb-6-safe {
    padding-bottom: 1.5rem;
}

@supports(padding: max(0px)) {
    .pb-6-safe {
        padding-bottom: ~"max(1.5rem, env(safe-area-inset-bottom))";
    }
}
```
