### ISSUE TITLE
Gulp Build Chain - `@apply` cannot be used with... - Trying to Solve with postcss-import

### ISSUE THREAD

**Issue by brianlarson** [tailwindcss/discuss#143]
First off... I ❤️ Tailwind CSS. It's so freeing to not have to name stuff. SO freeing.

I seem to be having the same problem with my Gulp build as mentioned in [this issue](https://github.com/tailwindcss/discuss/issues/71) with Laravel Mix. A little background... I'm using Foundation alongside Tailwind to utilize Foundation's JS components (still too 😬 to _roll my own_) and have most of the Sass partials commented out. Hopefully I just need some tweaks to my Gulpfile as I think I'm not properly implementing PostCSS Import!

## Full Error
```
[15:01:14] 'sass' errored after 920 ms
[15:01:14] CssSyntaxError in plugin "gulp-postcss"
Message:
    /Users/brianlarson/Sites/scg-craft/src/assets/scss/app.css:1479:3: `@apply` cannot be used with `.bg-blue` because `.bg-blue` either cannot be found, or it's actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.bg-blue` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  1477 |   */
  1478 | .btn-blue {
> 1479 |   @apply .bg-blue .text-white; }
       |   ^
  1480 |

[15:01:14] 'build' errored after 928 ms
[15:01:14] 'default' errored after 930 ms
[15:01:14] The following tasks did not complete: javascript, images
[15:01:14] Did you forget to signal async completion?
```

## sass() Function in gulpfile.babel.js
```
function sass() {
  var tailwindcss = require('tailwindcss');
  var autoprefixer = require('autoprefixer');
  let atImport = require('postcss-import');
  var plugins = [
    tailwindcss('src/assets/js/tailwind.js'),
    autoprefixer({browsers: ['last 1 version']}),
    atImport(),
  ];
  return gulp.src(['src/assets/scss/app.scss'])
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      includePaths: PATHS.sass
    })
    .on('error', $.sass.logError))
    .pipe($.postcss(plugins))
    .pipe($.if(!PRODUCTION, $.sourcemaps.write()))
    // Comment in the pipe below to run UnCSS in production
    // .pipe($.if(PRODUCTION, $.uncss(UNCSS_OPTIONS)))
    .pipe($.if(PRODUCTION, $.cleanCss({ compatibility: 'ie9' })))
    .pipe(gulp.dest(PATHS.dist + '/css'))
    .pipe(browser.reload({ stream: true }));
}
gulp.task('sass', sass);
```

## config.yml
```
# Your project's server will run on localhost:xxxx at this port
PORT: 3000

# Browsersync config
BROWSER: 
  proxy: "https://scg-craft.dev"
  key: "/Users/brianlarson/Sites/_ssl/localhost/localhost.key"
  cert: "/Users/brianlarson/Sites/_ssl/localhost/localhost.crt"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  twig:
    - "templates/**/*.twig"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "web/assets/template" 
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}{,/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
```

## package.json
```
{
  "name": "scg-craft",
  "version": "1.0.0",
  "description": "SCG Craft CMS starter template with Foundation and Tailwind CSS",
  "main": "gulpfile.babel.js",
  "scripts": {
    "start": "gulp",
    "build": "gulp build --production",
    "watch": "gulp watch"
  },
  "author": "SCG <admin@scgpr.com>",
  "dependencies": {
    "babel-register": "^6.26.0",
    "foundation-sites": "~6.4.3",
    "jquery": ">=3.0.0",
    "motion-ui": "~1.2.2",
    "tailwindcss": "^0.5.1",
    "what-input": "^4.1.3"
  },
  "devDependencies": {
    "autoprefixer": "^8.2.0",
    "babel-core": "^6.24.1",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.3.13",
    "browser-sync": "^2.10.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-babel": "^6.1.2",
    "gulp-clean-css": "^3.9.3",
    "gulp-cli": "^1.2.1",
    "gulp-concat": "^2.5.2",
    "gulp-extname": "^0.2.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.2.1",
    "gulp-load-plugins": "^1.1.0",
    "gulp-postcss": "^7.0.1",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.2.0",
    "gulp-uncss": "^1.0.1",
    "js-yaml": "^3.4.6",
    "parallax.js": "^0.1.0",
    "postcss-import": "^11.1.0",
    "rimraf": "^2.4.3",
    "vinyl-named": "^1.1.0",
    "webpack": "^2.6.1",
    "webpack-stream": "^3.2.0",
    "yargs": "^3.8.0"
  },
  "repository": {
    "type": "git",
    "url": "https://bitbucket.org/scgpr/scg-craft"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  },
  "private": true,
  "optionalDependencies": {}
}
```
