### ISSUE TITLE
Any plans for Opacity Utility Classes?

### ISSUE THREAD

**Issue by nkeena** [tailwindcss/discuss#21]
Are there plans to add utility classes to control the opacity of a background or element?

Maybe something like: `o-{level}` or  `opacity-{level}`.

Example:
```html
<div class="bg-blue w-64 h-64 opacity-10"></div>
```
The CSS output would be something like this:
```css
opacity-10 {
    opacity: 0.1;
    filter: alpha(opacity=10); /* For IE8 and earlier */
}
```
