### ISSUE TITLE
Issue with processCssUrls: true

### ISSUE THREAD

**Issue by puncoz** [tailwindcss/discuss#231]
I am using tailwindcss with laravel using laravel mix. And now i encounter a issue with `processCssUrls: true` options.

As per tailwindcss' documentation, we need to use following in laravel mix:

```
options({
    processCssUrls: false,
    postCss: [tailwindCss("./resources/assets/front/sass/tailwind.js")],
})
```

But with that `processCssUrls: false` my images and svgs url used in sass/scss dont comes to public directory. And if turned that true, ie. `processCssUrls: true` tailwind wont compiled.

**Comment by adamwathan** [comment]
I think your best option is to use absolute paths for all of your URLs instead of relative paths, if I remember what the feature does correctly.

Can you share an example of some CSS that doesn't work properly with that option disabled?

**Comment by puncoz** [comment]
Here's my custom sass which i include at last in `app.scss` where tailwindcss' preflight and other stuff included

```
li {
        &:before {
            content: '';
            background-repeat: no-repeat;
            background-size: 20px;
            width: 20px;
            height: 20px;
            display: inline-block;
            position: absolute;
            left: 0;
        }

        &.tick {
            &:before {
                background-image: url(./../../images/icons/ic-tick.svg);
            }
        }

        &.cross {
            &:before {
                width: 16px;
                height: 16px;
                top: 4px;
                background-image: url(./../../images/icons/ic-cross.svg);
                background-size: 16px;
            }
        }
    }
```

**Comment by adamwathan** [comment]
Got it, so what you want to do is write your image URLs relative the your web root, not relative to the Sass file you're in.

You _probably_ want this:

```scss
li {
    &:before {
        content: '';
        background-repeat: no-repeat;
        background-size: 20px;
        width: 20px;
        height: 20px;
        display: inline-block;
        position: absolute;
        left: 0;
    }

    &.tick {
        &:before {
            background-image: url(/images/icons/ic-tick.svg);
        }
    }

    &.cross {
        &:before {
            width: 16px;
            height: 16px;
            top: 4px;
            background-image: url(/images/icons/ic-cross.svg);
            background-size: 16px;
        }
    }
}
```

...assuming your images are in `/public/images/...`.

You'll need to put your public assets there yourself, as they won't be copied over.
