### ISSUE TITLE
config function not working

### ISSUE THREAD

**Issue by gempeler** [tailwindcss/discuss#285]
Hi, when I use config() im my tailwind-own.css, the values are not resolved. If I use theme(), everything works fine.

Here is my tailwind-own.css

```css
@tailwind base;
@tailwind components;

.btn-blue {
  background-color: theme("colors.blue.500");
  color: theme(colors.gray.500);
}

.btn-blue:hover {
  @apply bg-blue-700;
}

.lnx-container {
  @apply .w-full .px-3 .mx-auto;
}
@screen sm {
  .lnx-container {
    max-width: theme("screens.sm");
  }
}
@screen md {
  .lnx-container {
    max-width: config("theme.screens.md");
  }
}
@screen lg {
  .lnx-container {
    max-width: theme("screens.lg");
  }
}
@screen xl {
  .lnx-container {
    max-width: theme("screens.xl");
  }
}

@tailwind utilities;
```
My tailwind.js ist just the default one:

```javascript
// tailwind.config.js
module.exports = {
  theme: {},
  variants: {},
  plugins: []
};
```
So this setup generates this CSS:

```css
@media (min-width: 1024px)
<style>…</style>
.lnx-container {
    max-width: 1024px;
}

@media (min-width: 768px)
<style>…</style>
.lnx-container {
    max-width: config("theme.screens.md");
}
@media (min-width: 640px)
<style>…</style>
.lnx-container {
    max-width: 640px;
}
```

So **max-width: config("theme.screens.md");** is obviously wrong - the config function seems not to resolve it's argument.
Maybe I'am missing soomething, I'am quite new to tailwind ;-)
