### ISSUE TITLE
Operate theme function 

### ISSUE THREAD

**Issue by VeronQ** [tailwindcss/discuss#330]
Hello,

I'd like to use `SCSS operation` with values returned from tailwind `theme` function, but it doesn't seems to work.

 Is such thing even possible ?

**Example:**

```js
maxWidth: {
  container: '1192px'
}
```

```scss
.o-container {
    width: 100%;
    max-width: theme('maxWidth.container');
    margin: 0 auto;
    padding-right: 16px;
    padding-left: 16px;
}

.o-container--left {
  max-width: (theme('maxWidth.container') / 2); // <--- Just here
  margin-left: auto;
}
```

I know I could just set a new entry like `halfContainer` for example, but I would prefer not to.

Thank you for your help.
