### ISSUE TITLE
Font styles and variants - how to work with them?

### ISSUE THREAD

**Issue by nezaboravi** [tailwindcss/discuss#375]
Hello again, i have a a new question.
Not truly understand font families and how all that works.
What i must achieve is that on a page i have to use Roboto font. 
But somewhere its Roboto Light, Somewhere is Roboto Regular,, then somwhere Roboto Light regular etc..
What i manage to do is to extend default Theme and to ad Roboto as a default first font. 
So on my page i get Roboto, but i need Roboto Light,  Roboto regular, Roboto bold, regular light etc..
How can i achieve that? 
Here is preview from InVision board...
<img width="733" alt="Screenshot 2019-11-10 00 00 17" src="https://user-images.githubusercontent.com/1515172/68532253-ab541180-034d-11ea-875b-d9b2be78b9b8.png">

**Comment by adamwathan** [comment]
Hey! You need to add the font using `@font-face` rules, and specify which font file should be used for each font weight.

Here's a simple example:

```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light'), local('Roboto-Light'), url(https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2) format('woff2');
}
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2) format('woff2');
}
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 500;
  src: local('Roboto Medium'), local('Roboto-Medium'), url(https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2) format('woff2');
}
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 700;
  src: local('Roboto Bold'), local('Roboto-Bold'), url(https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2) format('woff2');
}
```

You can learn more about it here: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face
