### ISSUE TITLE
How to shared code?

### ISSUE THREAD

**Issue by MrJmpl3** [tailwindcss/discuss#428]
I will to create a UI components with Vue + Tailwind.

I look create component like the page: https://tailwindcss.com/docs/plugins/#adding-components

But have the problem:

Created a css class per components, this is unnecessary because I want reuse the generated classes of Tailwind like the good example of the part "Extracting HTML components" in https://tailwindcss.com/docs/extracting-components/#extracting-html-components

I think the best way for solved this problem is send my UI components like a template and not as package.

For example, I want a card:

I want shared my component like this, reusing the generated classes

```html
<div class="rounded shadow">
 Card
</div>
```

But with components CSS in JS, need add new class

```html
<div class="card ">
 Card
</div>
```

```css
.card {
 box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
 border-radius: .25rem;
}
```
