### ISSUE TITLE
"included in multiple rulesets" compiling error since Tailwind 1.2.0

### ISSUE THREAD

**Issue by danielbachhuber** [tailwindcss/discuss#438]
Hi,

We updated to Tailwind 1.2.0 this morning and now see this error when compiling:

```
`@apply` cannot be used with .grid because .grid is included in multiple rulesets.
```

Any ideas on how I could debug this?

Thanks!

**Comment by adamwathan** [comment]
Do you have your own custom class called `.grid` as well? Tailwind includes a `grid` class too now so when using `@apply` Tailwind might be seeing its own class + your custom class and erroring due to the ambiguity.

**Comment by danielbachhuber** [comment]
Ah!

> Do you have your own custom class called `.grid` as well?

No, but we have these two:

```css
.grid-span-full {
	grid-column: 1/-1;
}
.grid-dense {
	grid-auto-flow: dense;
}
```

Could one of those be the problem?
