### ISSUE TITLE
Multiple psuedo selectors

### ISSUE THREAD

**Issue by jaredmeakin** [tailwindcss/discuss#467]
Trivial example, but how would one enable variant support for multiple pseudo selectors?

````css
.button:hover:enabled {
   cursor: pointer;
}

.button:hover:disabled {
   cursor: not-allowed;
}
````

Thanks!
