### ISSUE TITLE
Export CSS output to JSON

### ISSUE THREAD

**Issue by rodrigoriome** [tailwindcss/discuss#470]
Hi!

Is there a way to export CSS output to JSON? It would work like so:

**CSS Output:**
```css
.mb\:12: {
    margin-bottom: 1.5rem;
}

.mb\:16: {
    margin-bottom: 2rem;
}
```

**JSON Output:**
```json
{
    "mb:12": "margin-bottom: 1.5rem;",
    "mb:16": "margin-bottom: 2rem;",
}
```

I'm developing an autocomplete plugin for IntelliJ IDEs, and that would be really helpful for me and also other people developing around Tailwind. I appreciate any tip you can give me.

Thanks!
