### ISSUE TITLE
Parent Hover changing Children (extra: webpack/mix all colors)

### ISSUE THREAD

**Issue by brnmonteiro** [tailwindcss/discuss#79]
**UPDATE**
In 0.3 version this is complished using `@group-hover` directive: https://github.com/tailwindcss/tailwindcss/releases#group-hover-variants

-----

I'm using this until official release (if have one).

**To complish:**

Set `.parent` class in the wrapper, and `.parent:hover:` prefix in children:

![captura de tela 2017-12-06 as 09 23 05](https://user-images.githubusercontent.com/6596579/33663517-710c43fe-da77-11e7-8387-d8240af8b8d4.jpg)

To make all colors available (using webpack) without tailwind modules what I did:

1. **Separate tailwind variables:**

```javascript
//taiwind_vars.js

var colors = global.colors = {
    'transparent': 'transparent',

    'black': '#222b2f',
    'grey-darkest': '#364349',
    'grey-darker': '#596a73'
     ...
}
```

```javascript
// tailwind.js

require('./tailwind_vars');

module.exports = {
    ...
}
```

2. **Inject `$colorList` variable in sass files:**

```javascript
// webpack.config.js

...

let _ = require('lodash');
require('./tailwind_vars');

module.exports = {
	...
   module: {
        rules: [{
            test: /\.scss$/,
            use: [{
                loader: "style-loader"
            }, {
                loader: "css-loader"
            }, {
                loader: "sass-loader",
                options: {
                    data: '$colorList: ' + _.join(_.keys(colors)) + ';'
                }
            }]
        }]
    }
}
```

or using mix

```javascript
// webpack.mix.js

...

let _ = require('lodash');
require('./tailwind_vars');

mix.sass('resources/assets/sass/main', 'public/css', {
    data: '$colorList: ' + _.join(_.keys(colors)) + ';',
})
```

3. **Loop var with SASS**

```sass
.parent {
    &:hover {
        @each $color in $colorList {
            .parent\:hover\:text-#{$color} {
                @apply .text-#{$color};
            }
            .parent\:hover\:bg-#{$color} {
                @apply .bg-#{$color};
            }
            .parent\:hover\:border-#{$color} {
                @apply .border-#{$color};
            }

            // extra classes
            .parent\:hover\:shadow {
                @apply .shadow;
            }
            .parent\:hover\:block {
                @apply .block;
            }
            
            // ...
        }
    }
}
```

**OUTPUT**: 
```css
.parent:hover .parent\:hover\:text-transparent {
  color: transparent;
}

.parent:hover .parent\:hover\:bg-transparent {
  background-color: transparent;
}

.parent:hover .parent\:hover\:border-transparent {
  border-color: transparent;
}

.parent:hover .parent\:hover\:shadow {
  -webkit-box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.10);
          box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.10);
}

.parent:hover .parent\:hover\:block {
  display: block;
}

.parent:hover .parent\:hover\:text-black {
  color: #222b2f;
}

.parent:hover .parent\:hover\:bg-black {
  background-color: #222b2f;
}

.parent:hover .parent\:hover\:border-black {
  border-color: #222b2f;
}

.parent:hover .parent\:hover\:shadow {
  -webkit-box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.10);
          box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.10);
}

.parent:hover .parent\:hover\:block {
  display: block;
}
...
```

Use with caution. Many classes will be injected. 
Create a tailwind plugin is another and better approach (read https://github.com/tailwindcss/tailwindcss/issues/219#issuecomment-349006078).
