### ISSUE TITLE
Order and grouping of classes within the Markup

### ISSUE THREAD

**Issue by terryupton** [tailwindcss/discuss#97]
Not necessarily TW specific, but does anyone have specific rules as to the order you write your TW classes within the markup?
Or any preferences on this? to make easier to digest?
e.g 
alphabetically, 
mobile first, 
group - layout or visual classes or all rw:classes

i.e
```class="sm:w-full // md:w-1/2 // lg:w-auto //// mb-4 // mr-4 // pr-4 //// text-grey // text-lg" 
```

It’s hard to be consistent when you are pro-trying/playing so it might be one that needs to be refactored, once blocks are completed.

I tend to group certain classes into spacing (margin/padding), typography, mobile first for structure. 
I know it is down to personal preference to some degree. Personally I find adding in the `//` helps, it is something I have done for a while now and it does make the classes more readable. Using TW I have thought to have the `////` to split the different groupings.

edit: a link regarding this grouping from Harry Roberts. https://csswizardry.com/2014/05/grouping-related-classes-in-your-markup/

**Comment by taylorbryant** [comment]
I normally group them alphabetically (prefixes not included).

```
<!-- Example -->
<div class="max-w-md mx-auto px-4 md:px-8 py-8 md:py-16 text-center"></div>
```

I write my CSS alphabetically, so it just felt natural. However, it can quickly look like spaghetti after a few days of not touching the files. I'm curious to see how others do this too 🤔.

**Comment by hacknug** [comment]
I personally do it in a similar way to the one described in this site: http://codeguide.co/#css-declaration-order

Here's an example with some of the differences. Special classes refers to classes you'd abstract with `@apply` or the one's you'd use to target elements via js.

```css
.declaration-order {
  /* Special Classes */

  /* Clearfixes and Floats */
  float: right;

  /* Positioning */
  z-index: 100;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;

  /* Box-model */
  display: block;
  width: 100px;
  height: 100px;
  flex-basis: 100px;
  justify-content: center;
  align-items: center;

  /* Color */
  color: #333;
  background-color: #f5f5f5;

  /* Typography */
  font-family: "Helvetica Neue", sans-serif;
  font-size: 13px; 
  line-height: 1.5;
  font-weight: normal;
  text-align: center;
  text-transform: uppercase;

  /* Visual */
  border: 1px solid #e5e5e5;
  border-radius: 3px;

  /* Misc */
  opacity: 1;
}
```
